server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-registration
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
